#!/bin/bash

# Setup script for version management
# This script sets up git hooks and gitignore entries

echo "🔧 Setting up version management..."

# Add .env.local to .gitignore if it's not already there
if ! grep -q ".env.local" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# Local environment variables (generated by version script)" >> .gitignore
    echo ".env.local" >> .gitignore
    echo "📝 Added .env.local to .gitignore"
fi

# Create initial .env.local if it doesn't exist
if [ ! -f .env.local ]; then
    echo "VITE_APP_VERSION=0.1.0" > .env.local
    echo "📄 Created initial .env.local"
fi

echo "✅ Version management setup complete!"
echo ""
echo "📋 What was set up:"
echo "  • .env.local added to .gitignore"
echo "  • Initial .env.local created"
echo ""
echo "🚀 The version will now automatically increment on every build!"

